### ISSUE TITLE
Most discussed bug for the last 30 days

### ISSUE THREAD

**Issue by jnerlich** [OpenReqEU/eclipse-plugin-vogella#10]
At the moment the most discussed bugs calls the bugs from the current month. This should be changed and the user should be able to set a time frame in his settings page.

**Comment by SimonScholz** [comment]
With the bugzilla api you can only ask for latest modify date and earlier.
So using a time span or time frame is not possible. You can just tell since when the last modification should have happend. 
The default is 30 days back.

**Comment by jnerlich** [comment]
I'm fine with this. Is it already implemented? At the moment I dont see anything in the most discussed bugs. See #12
