### ISSUE TITLE
Need at add explicit javax.annotation if running on Java 11

### ISSUE THREAD

**Issue by vogella** [OpenReqEU/eclipse-plugin-vogella#2]
@SimonScholz javax.annotation is not provided by the JRE with Java 11. I cc you here, as you may face this also with your customers. Fixed with 458695c1348b08f8d46e64a3964e404de6b8804b

**Comment by SimonScholz** [comment]
I thought having core.runtime in the classpath would add javax.annotation implicitly?

**Comment by vogella** [comment]
Iirc this was the case a few years ago but has been changed meanwhile

Am Do., 22. Nov. 2018, 12:37 hat Simon Scholz <notifications@github.com>
geschrieben:

**Comment by jnerlich** [comment]
Is is issue still open?

**Comment by vogella** [comment]
Nope
