### ISSUE TITLE
Add row 'created on' to the table of bugs

### ISSUE THREAD

**Issue by jnerlich** [OpenReqEU/eclipse-plugin-vogella#27]
The table should be enhanced with the created on attribute of a bug.

**Comment by SimonScholz** [comment]
@jonas-jonas Wir nutzen als backend dieses Projekt (https://github.com/OpenReqEU/eclipse-issue-prioritizer), welches die Ergebnisse der Priorisierung liefert. Aktuell wird dabei nicht das created date mitgeschickt.

**Comment by jnerlich** [comment]
Dieses Feld gibt es schon und heißt "creation_time”.

Hier die Stelle im Code:
https://github.com/OpenReqEU/eclipse-issue-prioritizer/blob/df55d54118f657836f066f8ca6e2d71c245ad6b0/application/controllers/recommendation_controller.py#L137

**Comment by jnerlich** [comment]
Solved with commit 04f6c3a7eda5d62ba9362d5400d137b580f23d73
