### ISSUE TITLE
Problems with Proxy

### ISSUE THREAD

**Issue by jnerlich** [OpenReqEU/eclipse-plugin-vogella#28]
The Eclipse Plugin can not be used if a Proxy is in place.

**Comment by vogella** [comment]
@SimonScholz just to confirm: the update site should now contain the fix, correct?

**Comment by SimonScholz** [comment]
@vogella  yes. :-)

**Comment by Bananeweizen** [comment]
Trying to update from an old version (some weeks ago) I get this:
```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Prioritizer 1.0.0.201904151333 (com.vogella.prioritizer.feature.feature.group 1.0.0.201904151333)
  Missing requirement: Service 1.0.0.201904151333 (com.vogella.prioritizer.service 1.0.0.201904151333) requires 'osgi.bundle; io.projectreactor.netty.reactor-netty 0.8.5' but it could not be found
  Cannot satisfy dependency:
    From: Prioritizer 1.0.0.201904151333 (com.vogella.prioritizer.feature.feature.group 1.0.0.201904151333)
    To: org.eclipse.equinox.p2.iu; com.vogella.prioritizer.service [1.0.0.201904151333,1.0.0.201904151333]
```

**Comment by vogella** [comment]
@SimonScholz please have a look and update this issue.

**Comment by SimonScholz** [comment]
> Trying to update from an old version (some weeks ago) I get this:
> 
> ```
> Cannot complete the install because one or more required items could not be found.
>   Software being installed: Prioritizer 1.0.0.201904151333 (com.vogella.prioritizer.feature.feature.group 1.0.0.201904151333)
>   Missing requirement: Service 1.0.0.201904151333 (com.vogella.prioritizer.service 1.0.0.201904151333) requires 'osgi.bundle; io.projectreactor.netty.reactor-netty 0.8.5' but it could not be found
>   Cannot satisfy dependency:
>     From: Prioritizer 1.0.0.201904151333 (com.vogella.prioritizer.feature.feature.group 1.0.0.201904151333)
>     To: org.eclipse.equinox.p2.iu; com.vogella.prioritizer.service [1.0.0.201904151333,1.0.0.201904151333]
> ```

I tried to make the netty reactor version work, but as a quickfix I removed it for now and the update site should work again.

But later I'll also create another version, which works with reactor netty.

**Comment by Bananeweizen** [comment]
Error messages have now changed to
```
No repository found containing: osgi.bundle,com.squareup.okhttp3.logging-interceptor,3.14.1
No repository found containing: osgi.bundle,com.squareup.okhttp3.okhttp,3.14.1
No repository found containing: osgi.bundle,com.squareup.okio,1.17.2
No repository found containing: osgi.bundle,com.vogella.common.core,1.0.0.201904162056
No repository found containing: osgi.bundle,com.vogella.prioritizer.core,1.0.0.201904180838
No repository found containing: org.eclipse.update.feature,com.vogella.prioritizer.feature,1.0.0.201904180919
No repository found containing: osgi.bundle,com.vogella.prioritizer.service,1.0.0.201904180919
No repository found containing: osgi.bundle,com.vogella.prioritizer.ui,1.0.0.201904161941
No repository found containing: osgi.bundle,com.vogella.rest.services,1.0.0.201904151259
No repository found containing: osgi.bundle,io.projectreactor.addons.reactor-extra,3.2.2.RELEASE
No repository found containing: osgi.bundle,io.projectreactor.reactor-core,3.2.8.RELEASE
```
You may want to revert https://github.com/OpenReqEU/eclipse-plugin-vogella/commit/3da974c0a54a63c05fdda0ac9581ba4dd86c1f9b, such that dependencies are contained in the update site again.

**Comment by jnerlich** [comment]
@vogella Could you please have a look at this?

**Comment by vogella** [comment]
@Bananeweizen update works for me in all scenarios. :-( I followed your suggestion and reverted  3da974c. Let me know if the update works now for you.

**Comment by jnerlich** [comment]
We tested the Plugin behind a Proxy and it works now. @Bananeweizen should you still have issues with this please reopen the issue.
