### ISSUE TITLE
Keywords shown after refresh

### ISSUE THREAD

**Issue by jnerlich** [OpenReqEU/eclipse-plugin-vogella#6]
If I change my settings,e.g another email address and then press refresh button the old keywords are shown until the new ones are ready. The user is unable to know if the refresh button did execute an action. 
The old keywords should be removed and an information saying 'loading...' should be displayed.

**Comment by SimonScholz** [comment]
Fixed with https://github.com/OpenReqEU/eclipse-plugin-vogella/commit/75e6ed65b8595f820477db4f21ac747a6961a95d
